// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpwrbwmrtbkyenmgthhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwd3Jid21ydGJreWVubWd0aGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjIxMTIsImV4cCI6MjA2NzIzODExMn0.mbDBmvg5AsND3BUCJIb8-IbsTtONqv_vazCgh3Xscn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});